default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit, manual]
repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
    - id: gitlint
      name: Check commit message, guideline on https://github.com/odoo/upgrade/wiki/commit-message
    - id: gitlint-ci
      name: Check commit message, guideline on https://github.com/odoo/upgrade/wiki/commit-message

  - repo: local
    hooks:
      - id: compile23
        name: Compile python files using the expected runtime version
        entry: ./tools/compile23.py
        language: script
        require_serial: true
        verbose: true
      - id: find-missing-links
        name: Find Missing Links
        entry: ./tools/find-missing-links.py
        language: script
        pass_filenames: false
        always_run: true
      - id: check-filenames
        name: Verify script filenames
        entry: ./tools/check-filenames.py
        language: script
      - id: no-license-comment
        name: Forbid LICENSE comments
        language: pygrep
        types: [python]
        entry: '^# .* LICENSE '
      - id: bad-import-000
        name: Incompatible import with old versions in tests and `0.0.0` scripts
        language: pygrep
        entry: '(from|import) odoo.upgrade\b'
        files: '^migrations/\w+/(tests|0\.0\.0)/.*\.py$'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
    - id: ruff-check
      name: Check code with Ruff, apply automatic fixes
      args: [ --fix, --exit-non-zero-on-fix ]
    - id: ruff-format
      name: Format code with Ruff automatically
  - repo: https://github.com/semgrep/pre-commit
    rev: v1.125.0
    hooks:
    - id: semgrep
      args: ['--disable-version-check', '--quiet', '--skip-unknown-extensions', '--metrics', 'off', '--oss-only', '--error', '--config', './semgrep.yaml']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-xml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-symlinks
    - id: debug-statements
